### PR TITLE
First naive approximation to real data and orthogonality

### PR DESCRIPTION
**Pull request by carrascomj**
This PR discusses the results of, first, applying the regularised horseshoe naive as previously stated in the document to the PRECISE database; and, second, iterating upon this with the orthogonal prior proposed in [Jauch et al., 2019](https://arxiv.org/pdf/1906.07684.pdf).

Note that the whole inference data was not included because these outputs are quite big.

### CODE REVIEW

**Comment by carrascomj** [comment]
To note, while [Roberts and Choudrey, 2005](https://www.robots.ox.ac.uk/~sjrob/Pubs/ica_eeg_pos.pdf) show the benefit of a positive constraint, they refer to the Activity matrix $A$ while $M$ ($s(t)$ in their notation) is left unconstrained, the opposite of what we are doing. I'll add that to the document.

**Review by teddygroves — APPROVED** [review]
Looks good - is it possible to add the image files too?

**Comment by carrascomj** [comment]
Oops, sorry, what images are missing?

**Comment by teddygroves** [comment]
Ah slight misunderstanding by me - there aren’t any missing image files but the images that get created by the quarto document can’t be seen in the html without re-running (or checking the docx). 

One solution is to set the `embed-resources` option so the images get saved in the html too, or you could just have the save the images to files.

Anyway feel free to merge before doing any of that!

**Pull request merged**
